### ISSUE TITLE
Small syntax issue in UAT-data-for-VRS

### ISSUE THREAD

**Issue by AustinGoodrich** [egite/Stratux-GDL90-to-SBS-Converter-for-Virtual-Radar-Server#1]
Looks like you and I had the same problem for VRS! Thank you for doing all the diligent work!

Here is the error I spotted from the following:
`echo "Create a receiver in VRS and point it to the IP address of this pi (which seems to be `hostname -I | sed 's: ::g'`) at port 33333."`

```
2024-05-31 18:33:45 (1.18 MB/s) - ‘UAT.sh’ saved [291/291]

./UAT-data-for-VRS.sh: 35: ./UAT-data-for-VRS.sh: Syntax error: "(" unexpected
```

**Comment by egite** [comment]
Hey.  Thanks for reaching out.  

There were two errors in the script which I fixed.   Sorry about that.  v1.1 was uploaded.

Let me know if v1.1 works for you.
